apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kibana
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 172-105-45-105.ip.linodeusercontent.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
